c/client-node: validate config token values
bartossh/Computantis pull request #213
Opened 2023-08-30 13:03 UTC by kmroz

Provides some basic port number and URL syntax validation.
Allows unit testing static functions (although @bartossh, you might have a better way to do this).

2023-08-30 13:31 UTC, bartossh requested changes
Great job. I like it. Please consider setting the formatting as the rest of the code before your PR. I already explained why in the comments.

Thanks. Keep introducing new ideas. Unit testing seems just right.

2023-08-30 13:31 UTC, bartossh commented on c/client-node/config/config.c
> +    if (regexec(&re, url, 0, NULL, 0) != 0) {
I have no favourite style and in Go for example you are forced to write like this:
```go
if statementIsTrue() {
    do()
}
```

But in C most people write like so: 
```c
if (statementIsTrue())
{
    do();
}
```

I prefer the go style probably because I'm used to that, but I think this is very idle to discuss details like that until they are not getting in the way of readability. 
Personal likes make it hard to bring any engineering value which is why I am not using what I like but rather going for what is more common.

Please keep the same style as I already started, until we introduce some kind of code formatting tool to clean things for us and then set up some rules.

Thanks for understanding.

2023-08-30 13:31 UTC, bartossh commented on c/client-node/config/config.c
> +        if (port < 1 || port > 65535) {
Small fix of a huge value. 🚀

2023-08-30 13:31 UTC, bartossh commented on c/client-node/config/config.h
> +#if UNIT_TEST
I like it. Simple straight forward solution. Fits `C` perfectly. Continue, please! 👍

2023-08-30 15:13 UTC, kmroz commented on c/client-node/config/config.c
> +    if (regexec(&re, url, 0, NULL, 0) != 0) {
ACK... I agree that keeping uniform style/formatting is immensely important.  These `if` statements poured out via muscle memory 😄 

Fixed in upcoming commit.

Per our chat earlier, I'd like to look into using `clang-format` along with a git pre-commit hook.  Then we'll essentially get what `gofmt` provides.

2023-08-31 05:32 UTC, bartossh approved these changes
LGTM!

2023-08-31 05:32 UTC, merged